# Generated by Django 5.2.17 on 2026-10-09 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def column_names(schema_editor, table):
    with schema_editor.connection.cursor() as cursor:
        return {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table)
        }


def add_voice_reply_schema(apps, schema_editor):
    """Preserve local databases that already contain the earlier private reply tables."""
    voice_draft = apps.get_model("replies", "VoiceDraft")
    comment = apps.get_model("replies", "Comment")
    tables = set(schema_editor.connection.introspection.table_names())
    if voice_draft._meta.db_table not in tables:
        schema_editor.create_model(voice_draft)
    field = comment._meta.get_field("draft")
    if field.column not in column_names(schema_editor, comment._meta.db_table):
        schema_editor.add_field(comment, field)


def remove_voice_reply_schema(apps, schema_editor):
    voice_draft = apps.get_model("replies", "VoiceDraft")
    comment = apps.get_model("replies", "Comment")
    field = comment._meta.get_field("draft")
    if field.column in column_names(schema_editor, comment._meta.db_table):
        schema_editor.remove_field(comment, field)
    if voice_draft._meta.db_table in schema_editor.connection.introspection.table_names():
        schema_editor.delete_model(voice_draft)


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_adaptedmessage'),
        ('replies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.CreateModel(
                name='VoiceDraft',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('recognized', models.TextField()),
                    ('converted', models.TextField()),
                    ('created_at', models.DateTimeField(auto_now_add=True)),
                    ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                    ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ],
            ),
            migrations.AddField(
                model_name='comment',
                name='draft',
                field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='replies.voicedraft'),
            ),
        ]),
        migrations.RunPython(add_voice_reply_schema, remove_voice_reply_schema),
    ]
