# Generated by Django 5.2.17 on 2026-10-06 00:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('invite_code', models.CharField(max_length=8, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('digest_time', models.TimeField(default=datetime.time(21, 0))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('owner', 'Owner'), ('father', 'Father'), ('mother', 'Mother'), ('grandma-father', 'Paternal grandmother'), ('grandma-mother', 'Maternal grandmother'), ('son', 'Son'), ('daughter', 'Daughter'), ('grandson', 'Grandson'), ('granddaughter', 'Granddaughter')], max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='families.familyroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('room', 'user'), name='unique_family_member'), models.UniqueConstraint(fields=('room', 'slot'), name='unique_family_slot')],
            },
        ),
    ]
