# Generated by Django 5.2.17 on 2026-10-02 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=12)),
                ('window_start', models.DateTimeField(null=True)),
                ('window_end', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posts', models.ManyToManyField(to='posts.post')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to='families.familyroom')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('room', 'date'), name='unique_daily_digest')],
            },
        ),
    ]
